<?php

namespace CovoiturageBundle\Repository;

/**
 * ReservTrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservTrajetRepository extends \Doctrine\ORM\EntityRepository
{
}
